### PR TITLE
FIX: Increment document fetcher

### LINKED ISSUE #52: DocumentChunkFetcher does not increment its fetcher, causing an infinite loop
## Module version

>=2.0.0

## Problem statement

`DocumentChunkFetcher::chunk()` does not increment its fetcher, so this just ends up being an infinite loop.

This was spotted when running an `IndexJob` with an document that has some sort of dependent documents.

I noticed that the method signature for `DocumentFetcher::fetch()` changed, but this class wasn't updated, so probably missed?

## Steps to reproduce

1. With some minimal config:

```yml
Page:
  fields:
    parent_title:
      property: 'Parent.Title'
```

2. Publish a change to queue a single `IndexJob`

### Expected outcome

The job completes as normal

### Actual outcome

The job never completes, blocking others in the queue

### PR DESCRIPTION
**Pull request by Cambis**
Resolves #52

### CODE REVIEW

File: tests/Service/DocumentChunkFetcherTest.php [hunk 1]
```diff
@@ -0,0 +1,24 @@
+<?php
+
+namespace SilverStripe\Forager\Tests\Service;
+
+use SilverStripe\Dev\SapphireTest;
+use SilverStripe\Forager\Interfaces\DocumentInterface;
+use SilverStripe\Forager\Service\DocumentChunkFetcher;
+use SilverStripe\Forager\Tests\Fake\DocumentFetcherFake;
+
+class DocumentChunkFetcherTest extends SapphireTest
```
Comment (lianna-blanca) [inline tests/Service/DocumentChunkFetcherTest.php]: This test runs fun and confirms the offset works, but can you please add a test to check that the loop is stopped correctly / that the break condition is hit when `$count < $batchSize`, using different batch sizes? 

A test to check the deprecation warning would also be nice.

File: tests/Service/DocumentChunkFetcherTest.php [hunk 2]
```diff
@@ -0,0 +1,24 @@
...
+{
+    public function testChunk(): void
+    {
+        $fetcher = DocumentFetcherFake::singleton();
```
Comment (lianna-blanca) [inline tests/Service/DocumentChunkFetcherTest.php]: Using `::singleton()` could result in data state leaking into other tests - please use either `::create()` or add a `setUp()` function to to make sure the offset is cleanly reset for each test.

**Review by lianna-blanca — CHANGES_REQUESTED** [review]
This fix works great; I have a few suggestions to strengthen the test.

**Comment by Cambis** [comment]
Hi @lianna-blanca thanks for the suggestions :) I've applied them
